# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_robot_driver/Odom_data.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Odom_data(genpy.Message):
  _md5sum = "4e66c9f8493a867e4988030ed11fbd23"
  _type = "my_robot_driver/Odom_data"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
float64 x
float64 y
float64 theta
float64 d_theta
float64 vel_l
float64 vel_r
uint16 counter_l
uint16 counter_r"""
  __slots__ = ['x','y','theta','d_theta','vel_l','vel_r','counter_l','counter_r']
  _slot_types = ['float64','float64','float64','float64','float64','float64','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,theta,d_theta,vel_l,vel_r,counter_l,counter_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Odom_data, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.theta is None:
        self.theta = 0.
      if self.d_theta is None:
        self.d_theta = 0.
      if self.vel_l is None:
        self.vel_l = 0.
      if self.vel_r is None:
        self.vel_r = 0.
      if self.counter_l is None:
        self.counter_l = 0
      if self.counter_r is None:
        self.counter_r = 0
    else:
      self.x = 0.
      self.y = 0.
      self.theta = 0.
      self.d_theta = 0.
      self.vel_l = 0.
      self.vel_r = 0.
      self.counter_l = 0
      self.counter_r = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d2H().pack(_x.x, _x.y, _x.theta, _x.d_theta, _x.vel_l, _x.vel_r, _x.counter_l, _x.counter_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.x, _x.y, _x.theta, _x.d_theta, _x.vel_l, _x.vel_r, _x.counter_l, _x.counter_r,) = _get_struct_6d2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d2H().pack(_x.x, _x.y, _x.theta, _x.d_theta, _x.vel_l, _x.vel_r, _x.counter_l, _x.counter_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.x, _x.y, _x.theta, _x.d_theta, _x.vel_l, _x.vel_r, _x.counter_l, _x.counter_r,) = _get_struct_6d2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d2H = None
def _get_struct_6d2H():
    global _struct_6d2H
    if _struct_6d2H is None:
        _struct_6d2H = struct.Struct("<6d2H")
    return _struct_6d2H
